name: Portfolio

on:
  push:
    branches:   
      - main
      - backend
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Check-health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: HTML Validation
        run: npx htmlhint "Frontend/*.html" 
      
      - run: echo "All good"




